#!/usr/bin/env tsx
/**
 * Build script: generates IIFE strings for all built-in packages.
 *
 * Ported into cross-q-context from the old app's `@requestly/sandbox-engine` so the
 * OSS package owns its own vendoring toolchain (the deleted app packages carried the
 * generator; only its OUTPUT — `vendor-iifes.ts` — was copied here). Now `npm run
 * generate:vendor` reproduces that file from the registry, so adding or upgrading a
 * bundled library is a registry + devDependency change, not a hand-edited 2 MB blob.
 *
 * Two sources:
 *   1. EXTERNAL_BUILTIN_PACKAGES — the IIFE-bundled npm packages (lodash, xml2js, …).
 *   2. NODE_BUILTIN_PACKAGES with `globalName` + `polyfillEntry` — Node built-ins
 *      served in Safe mode by an in-isolate pure-JS polyfill bundle (`events`).
 *      Most `source_bundle` Node built-ins have neither field and stay Node-native
 *      (Developer) / IMPOSSIBLE (Safe) — only the opted-in ones are bundled here.
 *
 * Bundles each entry as an IIFE via esbuild and writes the result to
 * src/runtime/engine/vendor-codegen/vendor-iifes.ts, keyed by the registry `id`.
 *
 * Run manually — `npm run generate:vendor` — whenever a bundled library is added or
 * upgraded (a registry entry + a devDependency change), then commit the regenerated
 * vendor-iifes.ts. It is deliberately NOT part of `build:runtime`: it needs the source
 * packages + esbuild as devDeps and its output is committed, so a normal build (and any
 * consumer install) uses the committed file rather than re-bundling every time.
 */

import { createRequire } from 'node:module';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { build } from 'esbuild';
import * as prettier from 'prettier';

import { EXTERNAL_BUILTIN_PACKAGES, NODE_BUILTIN_PACKAGES } from '../../definitions/builtInPackages/index.js';

import type { NodeBuiltinPackage } from '../../definitions/builtInPackages/index.js';

const require = createRequire(import.meta.url);

/**
 * The Node built-ins opted into an in-isolate polyfill bundle (both `globalName`
 * and `polyfillEntry` set). Widened to `NodeBuiltinPackage[]` by assignment so the
 * optional fields are visible past the `as const` union of the literal.
 */
const ALL_NODE_BUILTINS: readonly NodeBuiltinPackage[] = NODE_BUILTIN_PACKAGES;
const POLYFILL_NODE_BUILTINS: readonly NodeBuiltinPackage[] = ALL_NODE_BUILTINS.filter(
  (p) => p.globalName !== undefined && p.polyfillEntry !== undefined,
);

const OUTPUT_FILE = path.resolve(import.meta.dirname, 'vendor-iifes.ts');

/** Bundle a resolved entry point into a minified IIFE string on `globalName`. */
async function bundleIife(id: string, entryPoint: string, globalName: string): Promise<string> {
  // platform: 'node' resolves CJS main fields and handles node: protocol. Node
  // built-ins the bundled package require() (events, crypto, timers, …) are left
  // as external require() calls — Developer's require() delegates them to Node,
  // and Safe's in-isolate require chain resolves them via its own registry
  // (needs_bridge globals, or a polyfill IIFE like `events`). Browserify polyfills
  // (events, …) are self-contained, so they bundle with no external requires.
  const result = await build({
    entryPoints: [entryPoint],
    format: 'iife',
    globalName,
    bundle: true,
    platform: 'node',
    minify: true,
    write: false,
  });
  const output = result.outputFiles[0];
  if (!output) {
    throw new Error(`esbuild produced no output for ${id}`);
  }
  return output.text;
}

async function main(): Promise<void> {
  const entries: string[] = [];

  for (const pkg of EXTERNAL_BUILTIN_PACKAGES) {
    const code = await bundleIife(pkg.id, require.resolve(pkg.entry), pkg.globalName);
    entries.push(`  '${pkg.id}': ${JSON.stringify(code)},`);
  }

  // Node built-ins opted into an in-isolate polyfill bundle (Safe mode). `events`
  // is resolved via its `polyfillEntry` ('events/') so we bundle the npm `events`
  // package (Node's events module verbatim), NOT Node's built-in of the same name.
  for (const pkg of POLYFILL_NODE_BUILTINS) {
    if (pkg.globalName === undefined || pkg.polyfillEntry === undefined) continue;
    const code = await bundleIife(pkg.id, require.resolve(pkg.polyfillEntry), pkg.globalName);
    entries.push(`  '${pkg.id}': ${JSON.stringify(code)},`);
  }

  // Precise key union so consumers keep dotted access (`VENDOR_IIFES.chai`) and no
  // `| undefined`: the external ids (`ExternalBuiltinPackageId`) plus each polyfill
  // Node-built-in id as a string literal. Generated, so it can never drift.
  const polyfillKeyUnion = POLYFILL_NODE_BUILTINS.map((p) => `'${p.id}'`).join(' | ');
  const keyType =
    polyfillKeyUnion.length > 0 ? `ExternalBuiltinPackageId | ${polyfillKeyUnion}` : 'ExternalBuiltinPackageId';

  const content = `// Auto-generated by generate-vendor-iifes.ts — do not edit.
import type { ExternalBuiltinPackageId } from '../../definitions/builtInPackages/index.js';

/**
 * IIFE strings keyed by registry \`id\` — every EXTERNAL_BUILTIN_PACKAGES entry plus
 * the Node built-ins served by an in-isolate polyfill bundle (e.g. \`events\`). The
 * key union is generated from both registries so it cannot drift.
 */
export const VENDOR_IIFES: Record<${keyType}, string> = {
${entries.join('\n')}
};
`;

  // Format with any resolved Prettier config before writing, so the generated output
  // matches what a format check would expect rather than leaving the file dirty.
  const formatted = await prettier.format(content, {
    ...(await prettier.resolveConfig(OUTPUT_FILE)),
    parser: 'typescript',
  });

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, formatted);

  console.log(
    `Generated vendor IIFEs for ${EXTERNAL_BUILTIN_PACKAGES.length} external packages + ${POLYFILL_NODE_BUILTINS.length} node-builtin polyfill(s) → ${OUTPUT_FILE}`,
  );
}

void main();
