//! `rq check` — read every file the way a run would, and report what a run would trip over.
//!
//! These files are edited by hand and generated by scripts, so the failure that matters is
//! the one that stays quiet: a `parents:` naming a request that was renamed, a `{{token}}`
//! nothing provides (which is *sent literally*, and comes back as a puzzling 401), a
//! `capture:` path that can never match, a `-- view --` whose template stopped parsing.
//! Every one of those runs "fine" until it doesn't.
//!
//! The rule for severity is deliberately mechanical: **Error** is something that cannot work
//! — a file that does not parse, a parent that does not resolve, a body file that is not
//! there. **Warning** is something a run does anyway while telling you it did, and the
//! canonical case is an unresolved variable: rq notes it and sends the text as written, so
//! calling it an error here would contradict what the run actually does.

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::path::PathBuf;

use crate::project::{Entry, Kind, Project};
use rq_doc::Document;

/// The roots a `capture:` path or a `-- view --` template can start from. Set by
/// `run::context_of`; a path starting anywhere else can never match anything.
const CONTEXT_ROOTS: &[&str] = &[
    "response",
    "status",
    "status_text",
    "headers",
    "body",
    "time_ms",
    "bytes",
    "vars",
    "request",
];

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum Level {
    /// A run cannot do what the file says.
    Error,
    /// A run will proceed, and will be worse for it.
    Warning,
}

impl Level {
    pub fn as_str(&self) -> &'static str {
        match self {
            Level::Error => "error",
            Level::Warning => "warning",
        }
    }
}

#[derive(Clone, Debug)]
pub struct Finding {
    pub level: Level,
    /// Which file, named the way the CLI names it (`github/issues`).
    pub at: String,
    pub message: String,
    /// What to do about it, when there is something specific to say.
    pub hint: Option<String>,
}

impl Finding {
    fn error(at: &str, message: impl Into<String>) -> Finding {
        Finding {
            level: Level::Error,
            at: at.to_string(),
            message: message.into(),
            hint: None,
        }
    }

    fn warn(at: &str, message: impl Into<String>) -> Finding {
        Finding {
            level: Level::Warning,
            at: at.to_string(),
            message: message.into(),
            hint: None,
        }
    }

    fn with_hint(mut self, hint: impl Into<String>) -> Finding {
        self.hint = Some(hint.into());
        self
    }
}

/// Everything wrong with this project, worst first, then by file.
pub fn check(project: &Project, environment: Option<&str>) -> Vec<Finding> {
    let mut out = Vec::new();

    // Files that looked like requests and weren't. The scan already worked this out; it is
    // reported here because `rq l` mentions it in passing and `rq check` is where someone
    // goes to find out what is wrong.
    for note in &project.notes {
        let (at, message) = note.split_once(": ").unwrap_or(("project", note));
        out.push(Finding::error(at, message.to_string()));
    }

    // Names something outside the request provides. Two deliberate choices here, both
    // learned from the first run of this check reporting four things that were fine:
    //
    // 1. **Declared, not resolved.** `GH_TOKEN: { env: GH_TOKEN }` provides a name whether or
    //    not that variable is exported in this shell. Checking the files must not depend on
    //    the state of the machine checking them, or CI and a laptop disagree.
    // 2. **Every environment, unless one is named.** Bare `rq check` asks "do these files
    //    hang together"; a name defined in `env/staging.md` is defined. `rq check -e staging`
    //    is the narrower question, and then only that environment counts.
    let mut ambient: HashSet<String> = project.dotenv().into_iter().map(|(k, _)| k).collect();
    let envs: Vec<String> = match environment {
        Some(name) => vec![name.to_string()],
        None => project.environments(),
    };
    for name in &envs {
        if let Ok((doc, _)) = project.load_env(name) {
            ambient.extend(doc.front.vars.iter().map(|(k, _)| k.clone()));
        }
    }
    // The project's own index.md is a collection like any other, but it has no entry in the
    // tree to be an ancestor of anything — so its declarations are gathered once, here.
    if let Ok(Some((root, _))) = project.root_collection() {
        ambient.extend(root.front.vars.iter().map(|(k, _)| k.clone()));
        ambient.extend(root.front.capture.iter().map(|(k, _)| k.clone()));
    }

    for name in project.environments() {
        if let Err(e) = project.load_env(&name) {
            out.push(Finding::error(&format!("env/{name}"), e.to_string()));
        } else if let Ok((_, notes)) = project.load_env(&name) {
            for note in notes {
                out.push(Finding::warn(&format!("env/{name}"), note.to_string()));
            }
        }
    }

    for (idx, entry) in project.entries.iter().enumerate() {
        // A collection with no index.md is a directory, and has nothing to check.
        if entry.kind == Kind::Collection && project.load_collection(idx).ok().flatten().is_none() {
            continue;
        }
        let (doc, notes) = match project.load(idx) {
            Ok(loaded) => loaded,
            Err(e) => {
                out.push(Finding::error(&entry.rel, e.to_string()));
                continue;
            }
        };
        for note in notes {
            out.push(Finding::warn(&entry.rel, note.to_string()));
        }
        check_document(project, idx, entry, &doc, &ambient, &mut out);
    }

    check_duplicate_names(project, &mut out);
    check_cycles(project, &mut out);

    out.sort_by(|a, b| a.level.cmp(&b.level).then(a.at.cmp(&b.at)));
    out
}

fn check_document(
    project: &Project,
    idx: usize,
    entry: &Entry,
    doc: &Document,
    ambient: &HashSet<String>,
    out: &mut Vec<Finding>,
) {
    let at = &entry.rel;

    // `parents:` — the reference that breaks when somebody renames a file.
    for parent in &doc.front.parents {
        if let Err(e) = project.resolve(parent) {
            out.push(
                Finding::error(at, format!("`parents: [{parent}]` — {e}"))
                    .with_hint("run `rq l` for the names this project has"),
            );
        }
    }

    // `capture:` — a path that starts somewhere the response context has no root can never
    // match, so it is worth saying now rather than as "nothing at `…`" on every run.
    for (key, path) in &doc.front.capture {
        let root = path.split('.').next().unwrap_or("").trim();
        let root = root.split('[').next().unwrap_or(root);
        if !CONTEXT_ROOTS.contains(&root) {
            out.push(
                Finding::error(at, format!("`capture: {key}: {path}` starts at `{root}`"))
                    .with_hint(format!(
                        "paths start at one of: {}",
                        CONTEXT_ROOTS.join(", ")
                    )),
            );
        }
    }

    // `-- view --` is a template, and a template that no longer parses takes the whole
    // response down with it at the very end of a run.
    if let Some(view) = doc.section("view") {
        let mut env = minijinja::Environment::new();
        if let Err(e) = env.add_template("view", view) {
            out.push(Finding::error(
                at,
                format!("`-- view --` does not parse: {e}"),
            ));
        }
    }

    // A body read from a file that is not there.
    if let Some(file) = &doc.front.file {
        if !file.contains("{{") {
            let path = entry.dir().join(file);
            if !path.is_file() && !project.is_converted() {
                out.push(Finding::error(at, format!("`file: {file}` is not there")));
            }
        }
    }

    // Variables nothing provides. A run substitutes what it can, notes the rest, and sends
    // them **as written** — which is how `Authorization: Bearer {{TOKEN}}` becomes a 401 that
    // looks like a credentials problem rather than a spelling one.
    let mut known: HashSet<String> = ambient.clone();
    for i in project.ancestors(idx).into_iter().chain([idx]) {
        if let Ok((d, _)) = project.load(i) {
            known.extend(declared(&d));
        }
    }
    // A `-- form --` field IS a variable — the form is how it gets a value. `{{text}}` in the
    // body of a request that declares a `text` field is the normal shape, not a mistake.
    if let Ok(fields) = doc.form() {
        known.extend(fields.into_iter().map(|f| f.name));
    } else {
        out.push(Finding::error(at, "`-- form --` is not valid YAML"));
    }
    // Anything a parent captures is provided by the time this request runs.
    for parent in &doc.front.parents {
        if let Ok(pidx) = project.resolve(parent) {
            for i in project.ancestors(pidx).into_iter().chain([pidx]) {
                if let Ok((d, _)) = project.load(i) {
                    known.extend(declared(&d));
                }
            }
        }
    }
    for name in used_variables(doc) {
        if !known.contains(&name) {
            out.push(
                Finding::warn(at, format!("`{{{{{name}}}}}` — nothing provides a value"))
                    .with_hint("a run sends it as written; declare it under `vars:`, put it in the environment, or pass `--var`"),
            );
        }
    }
}

/// Every name a document declares: prompted variables, captured values, form fields.
fn declared(doc: &Document) -> BTreeSet<String> {
    let mut out: BTreeSet<String> = doc.front.vars.iter().map(|(k, _)| k.clone()).collect();
    out.extend(doc.front.capture.iter().map(|(k, _)| k.clone()));
    if let Ok(fields) = doc.form() {
        out.extend(fields.into_iter().map(|f| f.name));
    }
    out
}

/// Every `{{ name }}` in the parts of a document a run substitutes.
fn used_variables(doc: &Document) -> BTreeSet<String> {
    let mut text = String::new();
    let front = &doc.front;
    for part in [front.url.as_deref(), front.file.as_deref()]
        .into_iter()
        .flatten()
    {
        text.push_str(part);
        text.push('\n');
    }
    for map in [
        Some(&front.headers),
        Some(&front.query),
        Some(&front.path_vars),
        front.form.as_ref(),
        front.form_data.as_ref(),
    ]
    .into_iter()
    .flatten()
    {
        for (k, v) in map {
            text.push_str(k);
            text.push('\n');
            text.push_str(v);
            text.push('\n');
        }
    }
    if let Some(auth) = &front.auth {
        text.push_str(&format!("{auth:?}\n"));
    }
    if let Some(body) = doc.section("body") {
        text.push_str(body);
    }
    // Declared defaults may themselves reference variables.
    for (_, spec) in &front.vars {
        if let Some(d) = &spec.default {
            text.push_str(d);
            text.push('\n');
        }
    }

    let mut names = BTreeSet::new();
    let bytes = text.as_bytes();
    let mut i = 0;
    while i + 1 < bytes.len() {
        if bytes[i] == b'{' && bytes[i + 1] == b'{' {
            if let Some(end) = text[i + 2..].find("}}") {
                let raw = text[i + 2..i + 2 + end].trim();
                // `{{ a.b }}` and filters belong to the view template, not to substitution.
                if !raw.is_empty() && !raw.contains('{') && !raw.contains('|') && !raw.contains(' ')
                {
                    names.insert(raw.to_string());
                }
                i += end + 4;
                continue;
            }
        }
        i += 1;
    }
    names
}

/// Two requests answering to the same short name: `rq r login` then has to pick, and picks
/// by erroring. Worth knowing before that happens.
fn check_duplicate_names(project: &Project, out: &mut Vec<Finding>) {
    let mut by_name: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for (_, entry) in project.requests() {
        by_name
            .entry(entry.name.as_str())
            .or_default()
            .push(entry.rel.as_str());
    }
    for (name, rels) in by_name {
        if rels.len() > 1 {
            out.push(
                Finding::warn(
                    rels[0],
                    format!("`{name}` is the short name of {} requests", rels.len()),
                )
                .with_hint(format!(
                    "`rq r {name}` will not know which; use the full path ({})",
                    rels.join(", ")
                )),
            );
        }
    }
}

/// `parents:` describing a loop. A run would chase it forever, so it refuses; this says
/// where the loop is.
fn check_cycles(project: &Project, out: &mut Vec<Finding>) {
    fn walk(
        project: &Project,
        idx: usize,
        seen: &mut Vec<usize>,
        done: &mut HashSet<usize>,
        out: &mut Vec<Finding>,
    ) {
        if seen.contains(&idx) {
            let names: Vec<String> = seen
                .iter()
                .skip_while(|i| **i != idx)
                .chain([&idx])
                .map(|i| project.entries[*i].rel.clone())
                .collect();
            out.push(
                Finding::error(
                    &project.entries[idx].rel,
                    format!("`parents:` loops: {}", names.join(" → ")),
                )
                .with_hint("a request cannot depend on itself, however indirectly"),
            );
            return;
        }
        if !done.insert(idx) {
            return;
        }
        seen.push(idx);
        if let Ok((doc, _)) = project.load(idx) {
            for parent in &doc.front.parents {
                if let Ok(pidx) = project.resolve(parent) {
                    walk(project, pidx, seen, done, out);
                }
            }
        }
        seen.pop();
    }

    let mut done = HashSet::new();
    for (idx, _) in project.requests() {
        walk(project, idx, &mut Vec::new(), &mut done, out);
    }
}

// ---------------------------------------------------------------------------------------
// rq fmt
// ---------------------------------------------------------------------------------------

/// A file whose canonical form differs from what is on disk.
pub struct Unformatted {
    pub at: String,
    pub path: PathBuf,
    pub formatted: String,
}

/// Every document that would change if written back canonically.
///
/// Formatting is parse-then-write, which means it is defined by the same reader a run uses:
/// keys in a known order, one style of quoting, sections in the documented order. Frontmatter
/// keys and sections rq does not know are **preserved verbatim** — formatting a file must
/// never be how you discover that this build dropped something.
pub fn unformatted(project: &Project) -> Vec<Unformatted> {
    let mut out = Vec::new();
    if project.is_converted() {
        return out;
    }
    for (idx, entry) in project.entries.iter().enumerate() {
        if entry.kind == Kind::Collection && project.load_collection(idx).ok().flatten().is_none() {
            continue;
        }
        let path = entry.file();
        let Ok(original) = std::fs::read_to_string(&path) else {
            continue;
        };
        let Ok((doc, _)) = Document::parse(&original) else {
            continue; // a file that does not parse is `rq check`'s business, not `rq fmt`'s
        };
        let formatted = doc.write();
        if formatted != original {
            out.push(Unformatted {
                at: entry.rel.clone(),
                path,
                formatted,
            });
        }
    }
    for name in project.environments() {
        let path = project.env_path(&name);
        let Ok(original) = std::fs::read_to_string(&path) else {
            continue;
        };
        let Ok((doc, _)) = Document::parse(&original) else {
            continue;
        };
        let formatted = doc.write();
        if formatted != original {
            out.push(Unformatted {
                at: format!("env/{name}"),
                path,
                formatted,
            });
        }
    }
    out
}
