//! The script engine rq ships with: QuickJS, in this process, no node.
//!
//! rq used to spawn `node` on a runner script inside `packages/cross-q-context`. That works on
//! a development checkout and nowhere else — a binary installed from a tarball has no npm
//! install next to it, and telling someone to install node to run a `-- post --` block would
//! make scripting a feature only contributors have.
//!
//! **What is NOT reimplemented here.** The `rq.*` API, the pm→rq shims, chai, the require
//! chain and every capability shim are *source strings* that cross-q-context generates into
//! `assets/guest-bundle.json`. This host evaluates them, in the package's own order, in an
//! in-process QuickJS. So the semantics still have exactly one owner, and a change there
//! reaches rq by regenerating the bundle rather than by porting anything. That was the whole
//! argument for hosting cross-q-context instead of rewriting it; embedding it keeps the
//! argument intact while dropping the process.
//!
//! **What IS host code here**, because it is what node was doing:
//!
//! * the bridges the guest calls out to — console, the Node builtins (`Buffer`, `crypto`,
//!   `zlib`, `util.inspect`), `fetch`, `rq.sendRequest`, cookies, timers, `require`;
//! * `inflateMutations`, ported from `inflate-mutations.ts` including its rule that a script
//!   set never downgrades a `secret` to plaintext.
//!
//! **Blocking on purpose.** The published engine installs `fetch` as an asyncified host
//! function because it runs in an event loop. rq is a blocking CLI on `ureq`, and `await` on
//! a plain value is simply a resolved await — so every bridge here is synchronous and the
//! job queue is pumped after the script returns. One less machine to get wrong.

use std::cell::RefCell;
use std::rc::Rc;
use std::sync::OnceLock;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use anyhow::{anyhow, Context as _, Result};
use base64::Engine as _;
use rquickjs::{ArrayBuffer, Context, Ctx, Function, Object, Runtime, Value as JsValue};
use serde_json::{json, Map, Value};

use crate::script::{ScriptEngine, ScriptExecutionInput, ScriptExecutionResult};

/// The guest realm, generated by `packages/cross-q-context` and committed. CI regenerates it
/// and fails if this copy has drifted, so "the engine changed but rq didn't" is not a state
/// the repo can be in.
const BUNDLE_JSON: &str = include_str!("../assets/guest-bundle.json");

/// How long a script may run before the host stops pumping. Matches the engine's default.
const DEFAULT_TIMEOUT_MS: u64 = 5_000;

/// The parsed bundle. Parsed once — it is 2 MB, almost all of it vendored package sources
/// that are only evaluated if a script actually requires them.
struct Bundle {
    eval_order: Vec<(String, String)>,
    collect_expr: String,
    vendor: Value,
    require_table: Value,
    impossible: Value,
    node_builtins: Vec<String>,
}

fn bundle() -> &'static Bundle {
    static BUNDLE: OnceLock<Bundle> = OnceLock::new();
    BUNDLE.get_or_init(|| {
        let b: Value = serde_json::from_str(BUNDLE_JSON).expect("the embedded guest bundle parses");
        Bundle {
            eval_order: b["evalOrder"]
                .as_array()
                .expect("evalOrder")
                .iter()
                .map(|s| {
                    (
                        s["name"].as_str().unwrap_or_default().to_string(),
                        s["source"].as_str().unwrap_or_default().to_string(),
                    )
                })
                .collect(),
            collect_expr: b["collectExpr"].as_str().unwrap_or_default().to_string(),
            node_builtins: b["nodeBuiltins"]
                .as_array()
                .map(|a| {
                    a.iter()
                        .filter_map(|v| v.as_str().map(String::from))
                        .collect()
                })
                .unwrap_or_default(),
            vendor: b["vendor"].clone(),
            require_table: b["requireTable"].clone(),
            impossible: b["impossibleMessages"].clone(),
        }
    })
}

/// The engine. Stateless: every execution gets a fresh isolate, which is the isolation story
/// the published engine has too (one context per script, nothing carried over but the result).
pub struct EmbeddedEngine;

impl ScriptEngine for EmbeddedEngine {
    fn name(&self) -> &str {
        "embedded QuickJS (cross-q-context guest realm)"
    }

    fn execute(&self, input: &ScriptExecutionInput) -> Result<ScriptExecutionResult> {
        run(input)
    }
}

// ---------------------------------------------------------------------------------------
// The run
// ---------------------------------------------------------------------------------------

/// Everything the bridges collect while the script runs.
#[derive(Default)]
struct Collected {
    logs: Vec<Value>,
    /// Cookies by host, seeded from the input and mutated by `rq.cookies.jar()`.
    cookies: Map<String, Value>,
}

fn run(input: &ScriptExecutionInput) -> Result<ScriptExecutionResult> {
    let bundle = bundle();
    let deadline =
        Instant::now() + Duration::from_millis(input.timeout_ms.unwrap_or(DEFAULT_TIMEOUT_MS));

    let rt = Runtime::new().context("could not start QuickJS")?;
    let ctx = Context::full(&rt).context("could not create a QuickJS context")?;
    let state = Rc::new(RefCell::new(Collected::default()));

    let context_json =
        serde_json::to_string(&input.context).context("serialising the script context")?;
    let phase = serde_json::to_value(input.phase)?
        .as_str()
        .unwrap_or("pre")
        .to_string();
    let allowlist = serde_json::to_value(&input.context)?
        .get("hostAllowlist")
        .cloned()
        .unwrap_or_else(|| json!([]));

    // Phase 1 — install the host side, then build the guest realm.
    let setup: Result<()> = ctx.with(|ctx| {
        install_bridges(&ctx, &state)?;

        let g = ctx.globals();
        g.set("__rq_context_json", context_json.as_str())?;
        g.set("__rq_phase", phase.as_str())?;
        g.set("__rq_hostAllowlist_json", allowlist.to_string().as_str())?;
        ctx.eval::<(), _>("globalThis.__rq_context = JSON.parse(globalThis.__rq_context_json);")
            .map_err(|e| js_error(&ctx, e, "context-parse"))?;

        for (name, source) in &bundle.eval_order {
            ctx.eval::<(), _>(source.as_str())
                .map_err(|e| js_error(&ctx, e, name))?;
        }
        Ok(())
    });
    setup?;

    // Phase 2 — the script itself, wrapped exactly as the published host wraps it: an async
    // IIFE with a top-level catch, so a throw is a *result* with an error rather than a
    // vanished run.
    let wrapped = format!(
        "(async () => {{ try {{\n{}\n}} catch (e) {{ \
           globalThis.__rq_error = (e && e.message) ? String(e.message) : String(e); \
           globalThis.__rq_stack = (e && e.stack) ? String(e.stack) : ''; }} }})()",
        input.script
    );
    let thrown: Option<String> = ctx.with(|ctx| match ctx.eval::<JsValue, _>(wrapped.as_str()) {
        Ok(_) => None,
        // A syntax error never reaches the guest's catch — it fails to compile at all.
        Err(e) => Some(format!("{}", js_error(&ctx, e, "script"))),
    });
    if let Some(message) = thrown {
        return Ok(ScriptExecutionResult {
            error: Some(message),
            logs: drain_logs(&state),
            ..Default::default()
        });
    }

    // Phase 3 — settle. Pumping has to happen outside `ctx.with`: the runtime is borrowed for
    // the life of that closure, and draining from inside it panics.
    while rt.is_job_pending() {
        if Instant::now() > deadline {
            break;
        }
        let _ = rt.execute_pending_job();
    }

    // Phase 4 — drain the guest in one JSON string, then inflate host-side.
    let collected: Result<Value> = ctx.with(|ctx| {
        let raw: String = ctx
            .eval(bundle.collect_expr.as_str())
            .map_err(|e| js_error(&ctx, e, "collect"))?;
        let user_error: String = ctx.eval("globalThis.__rq_error || ''").unwrap_or_default();
        let mut v: Value = serde_json::from_str(&raw).context("the guest's collected JSON")?;
        if !user_error.is_empty() {
            v["error"] = Value::String(user_error);
        }
        Ok(v)
    });
    let collected = collected?;

    let context_value = serde_json::to_value(&input.context)?;
    let result = json!({
        "mutationDiff": inflate_mutations(collected.get("mutations").unwrap_or(&Value::Null), &context_value),
        "logs": drain_logs(&state),
        "testResults": collected.get("testResults").cloned().unwrap_or_else(|| json!([])),
        "requestMutationDiff": collected.get("requestMutations").and_then(|m| {
            (!m.as_array().map(|a| a.is_empty()).unwrap_or(true)).then(|| json!({ "headers": m }))
        }),
        "executionDirective": collected.get("executionDirective").cloned().unwrap_or(Value::Null),
        "error": collected.get("error").cloned().unwrap_or(Value::Null),
    });

    serde_json::from_value(result).context("the embedded engine produced an unreadable result")
}

fn drain_logs(state: &Rc<RefCell<Collected>>) -> Vec<crate::script::LogEntry> {
    let logs = std::mem::take(&mut state.borrow_mut().logs);
    logs.into_iter()
        .filter_map(|l| serde_json::from_value(l).ok())
        .collect()
}

/// Turn a QuickJS error into something that names the step and carries the guest's message.
fn js_error(ctx: &Ctx<'_>, err: rquickjs::Error, step: &str) -> anyhow::Error {
    let detail = ctx.catch();
    let message = detail
        .as_exception()
        .and_then(|e| e.message())
        .or_else(|| detail.as_string().and_then(|s| s.to_string().ok()))
        .unwrap_or_else(|| err.to_string());
    anyhow!("{step}: {message}")
}

// ---------------------------------------------------------------------------------------
// The bridges — what node was doing
// ---------------------------------------------------------------------------------------

fn install_bridges<'js>(ctx: &Ctx<'js>, state: &Rc<RefCell<Collected>>) -> Result<()> {
    let g = ctx.globals();

    // console — the guest pre-serialises its args, so only strings cross.
    let sink = state.clone();
    g.set(
        "__rq_console",
        Function::new(ctx.clone(), move |level: String, args_json: String| {
            let args: Value =
                serde_json::from_str(&args_json).unwrap_or_else(|_| json!([args_json]));
            sink.borrow_mut().logs.push(json!({
                "level": level,
                "args": args,
                "timestamp": now_millis(),
            }));
        })?,
    )?;

    // Deprecation notices and timer-callback throws: recorded, never fatal.
    g.set(
        "__rq_deprecation",
        Function::new(ctx.clone(), |_identifier: String, _shimmed: bool| {})?,
    )?;
    let sink = state.clone();
    g.set(
        "__rq_timerError",
        Function::new(ctx.clone(), move |message: String| {
            sink.borrow_mut().logs.push(json!({
                "level": "error", "args": [message], "timestamp": now_millis(),
            }));
        })?,
    )?;

    // Timers. rq runs one short script at a time, so an armed timer is a bounded blocking
    // sleep rather than a scheduler: `await setTimeout(f, 50)` waits 50ms and continues.
    // Two timers therefore run in sequence rather than interleaved — the one place this host
    // is deliberately simpler than the event-loop one, and the shape of script that would
    // notice is not the shape anyone writes in a request.
    g.set(
        "__rq_setTimer",
        Function::new(ctx.clone(), move |_guest_id: i64, ms: f64| {
            let capped = ms.clamp(0.0, 2_000.0) as u64;
            std::thread::sleep(Duration::from_millis(capped));
        })?,
    )?;
    g.set(
        "__rq_clearTimer",
        Function::new(ctx.clone(), |_guest_id: i64| {})?,
    )?;

    // require() — answered from the classification the bundle carries.
    g.set(
        "__rq_bundleRequire",
        Function::new(ctx.clone(), |ctx: Ctx<'js>, id: String| {
            resolve_require(ctx, id)
        })?,
    )?;

    // The Node builtins the shims call out to.
    g.set("__rq_buffer", Function::new(ctx.clone(), buffer_bridge)?)?;
    g.set("__rq_crypto", Function::new(ctx.clone(), crypto_bridge)?)?;
    g.set("__rq_zlib", Function::new(ctx.clone(), zlib_bridge)?)?;
    g.set(
        "__rq_util_inspect",
        Function::new(ctx.clone(), util_inspect_bridge)?,
    )?;

    // fetch + rq.sendRequest, both on ureq.
    g.set("__rq_fetch", Function::new(ctx.clone(), fetch_bridge)?)?;
    g.set(
        "__rq_runRequest",
        Function::new(ctx.clone(), run_request_bridge)?,
    )?;

    // The cookie jar: in-memory for the run, which is what a one-shot CLI can honestly offer.
    let sink = state.clone();
    g.set(
        "__rq_cookies",
        Function::new(ctx.clone(), move |ctx: Ctx<'js>, args: Object<'js>| {
            cookie_bridge(ctx, args, &sink)
        })?,
    )?;

    Ok(())
}

/// The host half of the require chain. The tiering is the bundle's; this just answers.
fn resolve_require<'js>(ctx: Ctx<'js>, id: String) -> rquickjs::Result<Object<'js>> {
    let b = bundle();
    let out = Object::new(ctx.clone())?;
    if let Some(entry) = b.require_table.get(&id) {
        if entry["kind"] == "bridge" {
            out.set("kind", "bridge")?;
            out.set("global", entry["global"].as_str().unwrap_or_default())?;
        } else {
            out.set("kind", "iife")?;
            out.set(
                "globalName",
                entry["globalName"].as_str().unwrap_or_default(),
            )?;
            out.set("code", b.vendor[&id].as_str().unwrap_or_default())?;
        }
        return Ok(out);
    }
    let bare = id.strip_prefix("node:").unwrap_or(&id);
    let message = if b.node_builtins.iter().any(|m| m == bare) {
        // A refused builtin says why it cannot work, rather than that it does not exist.
        b.impossible["other"]
            .as_str()
            .unwrap_or_default()
            .replace("%ID%", bare)
    } else {
        format!("Package '{id}' not found.")
    };
    Err(throw(ctx, &message))
}

fn throw(ctx: Ctx<'_>, message: &str) -> rquickjs::Error {
    match rquickjs::String::from_str(ctx.clone(), message) {
        Ok(s) => ctx.throw(s.into_value()),
        Err(e) => e,
    }
}

// --- Buffer ------------------------------------------------------------------------------

fn buffer_bridge<'js>(ctx: Ctx<'js>, req: Object<'js>) -> rquickjs::Result<Object<'js>> {
    let op: String = req.get("op")?;
    let encoding: String = req.get("encoding")?;
    let out = Object::new(ctx.clone())?;
    if op == "encode" {
        let input: String = req.get("input")?;
        let bytes = match encoding.as_str() {
            "utf8" | "utf-8" => input.into_bytes(),
            "hex" => hex::decode(&input).unwrap_or_default(),
            "base64" => base64::engine::general_purpose::STANDARD
                .decode(input.trim())
                .unwrap_or_default(),
            "base64url" => base64::engine::general_purpose::URL_SAFE_NO_PAD
                .decode(input.trim_end_matches('='))
                .unwrap_or_default(),
            "ascii" | "latin1" => input.chars().map(|c| c as u32 as u8).collect(),
            _ => return Err(throw(ctx, "Unsupported Buffer encoding in Safe mode")),
        };
        out.set("bytes", ArrayBuffer::new(ctx, bytes)?)?;
    } else {
        let bytes = bytes_of(&req, "bytes")?;
        let text = match encoding.as_str() {
            "utf8" | "utf-8" => String::from_utf8_lossy(&bytes).into_owned(),
            "hex" => hex::encode(&bytes),
            "base64" => base64::engine::general_purpose::STANDARD.encode(&bytes),
            "base64url" => base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(&bytes),
            "ascii" | "latin1" => bytes.iter().map(|b| *b as char).collect(),
            _ => return Err(throw(ctx, "Unsupported Buffer encoding in Safe mode")),
        };
        out.set("text", text)?;
    }
    Ok(out)
}

/// Read an ArrayBuffer (or TypedArray) property as bytes — how binary crosses the edge.
fn bytes_of<'js>(obj: &Object<'js>, key: &str) -> rquickjs::Result<Vec<u8>> {
    let v: JsValue<'js> = obj.get(key)?;
    if let Some(ab) = ArrayBuffer::from_value(v.clone()) {
        return Ok(ab.as_bytes().unwrap_or_default().to_vec());
    }
    if let Some(o) = v.as_object() {
        if let Ok(ab) = o.get::<_, ArrayBuffer<'js>>("buffer") {
            return Ok(ab.as_bytes().unwrap_or_default().to_vec());
        }
    }
    Ok(Vec::new())
}

// --- crypto ------------------------------------------------------------------------------

fn crypto_bridge<'js>(ctx: Ctx<'js>, req: Object<'js>) -> rquickjs::Result<Object<'js>> {
    use hmac::{KeyInit, Mac};
    let op: String = req.get("op")?;
    let out = Object::new(ctx.clone())?;
    match op.as_str() {
        "hash" => {
            let algo: String = req.get("algo")?;
            let data = bytes_of(&req, "data")?;
            let digest = match normalise_algo(&algo).as_str() {
                "md5" => {
                    use md5::Digest;
                    md5::Md5::digest(&data).to_vec()
                }
                "sha1" => {
                    use sha1::Digest;
                    sha1::Sha1::digest(&data).to_vec()
                }
                "sha256" => {
                    use sha2::Digest;
                    sha2::Sha256::digest(&data).to_vec()
                }
                "sha384" => {
                    use sha2::Digest;
                    sha2::Sha384::digest(&data).to_vec()
                }
                "sha512" => {
                    use sha2::Digest;
                    sha2::Sha512::digest(&data).to_vec()
                }
                other => return Err(throw(ctx, &format!("Unsupported hash algorithm '{other}'"))),
            };
            let encoding: String = req.get("outputEncoding").unwrap_or_else(|_| "hex".into());
            out.set("digest", encode_digest(&digest, &encoding))?;
        }
        "hmac" => {
            let algo: String = req.get("algo")?;
            let key = bytes_of(&req, "key")?;
            let data = bytes_of(&req, "data")?;
            let digest = match normalise_algo(&algo).as_str() {
                "sha256" => {
                    let mut m = <hmac::Hmac<sha2::Sha256> as KeyInit>::new_from_slice(&key)
                        .map_err(|_| throw(ctx.clone(), "invalid HMAC key"))?;
                    m.update(&data);
                    m.finalize().into_bytes().to_vec()
                }
                "sha512" => {
                    let mut m = <hmac::Hmac<sha2::Sha512> as KeyInit>::new_from_slice(&key)
                        .map_err(|_| throw(ctx.clone(), "invalid HMAC key"))?;
                    m.update(&data);
                    m.finalize().into_bytes().to_vec()
                }
                "sha1" => {
                    let mut m = <hmac::Hmac<sha1::Sha1> as KeyInit>::new_from_slice(&key)
                        .map_err(|_| throw(ctx.clone(), "invalid HMAC key"))?;
                    m.update(&data);
                    m.finalize().into_bytes().to_vec()
                }
                other => return Err(throw(ctx, &format!("Unsupported HMAC algorithm '{other}'"))),
            };
            let encoding: String = req.get("outputEncoding").unwrap_or_else(|_| "hex".into());
            out.set("digest", encode_digest(&digest, &encoding))?;
        }
        "randomBytes" => {
            let size: usize = req
                .get::<_, f64>("size")
                .unwrap_or(0.0)
                .clamp(0.0, 65_536.0) as usize;
            let mut bytes = vec![0u8; size];
            getrandom::fill(&mut bytes).map_err(|_| throw(ctx.clone(), "randomBytes failed"))?;
            out.set("bytes", ArrayBuffer::new(ctx, bytes)?)?;
        }
        "randomUUID" => {
            out.set("uuid", uuid::Uuid::new_v4().to_string())?;
        }
        other => return Err(throw(ctx, &format!("Unsupported crypto op '{other}'"))),
    }
    Ok(out)
}

fn normalise_algo(algo: &str) -> String {
    algo.to_ascii_lowercase().replace('-', "")
}

fn encode_digest(digest: &[u8], encoding: &str) -> String {
    match encoding {
        "base64" => base64::engine::general_purpose::STANDARD.encode(digest),
        "base64url" => base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(digest),
        "latin1" | "binary" => digest.iter().map(|b| *b as char).collect(),
        _ => hex::encode(digest),
    }
}

// --- zlib --------------------------------------------------------------------------------

fn zlib_bridge<'js>(ctx: Ctx<'js>, req: Object<'js>) -> rquickjs::Result<Object<'js>> {
    use flate2::read::{DeflateDecoder, DeflateEncoder, GzDecoder, GzEncoder};
    use std::io::Read;

    let op: String = req.get("op")?;
    let data = bytes_of(&req, "data")?;
    let level = flate2::Compression::default();
    let mut buf = Vec::new();
    let outcome = match op.as_str() {
        "deflate" => DeflateEncoder::new(&data[..], level).read_to_end(&mut buf),
        "inflate" => DeflateDecoder::new(&data[..]).read_to_end(&mut buf),
        "gzip" => GzEncoder::new(&data[..], level).read_to_end(&mut buf),
        "gunzip" => GzDecoder::new(&data[..]).read_to_end(&mut buf),
        other => return Err(throw(ctx, &format!("Unsupported zlib op '{other}'"))),
    };
    outcome.map_err(|e| throw(ctx.clone(), &format!("{op} failed: {e}")))?;
    let out = Object::new(ctx.clone())?;
    out.set("bytes", ArrayBuffer::new(ctx, buf)?)?;
    Ok(out)
}

// --- util.inspect ------------------------------------------------------------------------

/// Node's `util.inspect` over a pre-serialised value. This is the one bridge that
/// *approximates* rather than matches: node's formatter has many years of edge cases in it,
/// and the guest hands us JSON, so anything JSON dropped (functions, symbols, cycles) is
/// already gone before we see it. Objects and arrays are formatted node-style, which covers
/// what scripts actually inspect.
fn util_inspect_bridge<'js>(ctx: Ctx<'js>, req: Object<'js>) -> rquickjs::Result<Object<'js>> {
    let json: String = req.get("json").unwrap_or_default();
    let value: Value = serde_json::from_str(&json).unwrap_or(Value::String(json.clone()));
    let out = Object::new(ctx.clone())?;
    out.set("text", inspect(&value, 0))?;
    Ok(out)
}

fn inspect(value: &Value, depth: usize) -> String {
    match value {
        Value::Null => "null".into(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => format!("'{}'", s.replace('\'', "\\'")),
        _ if depth >= 4 => match value {
            Value::Array(_) => "[Array]".into(),
            _ => "[Object]".into(),
        },
        Value::Array(items) => {
            if items.is_empty() {
                return "[]".into();
            }
            let inner: Vec<String> = items.iter().map(|i| inspect(i, depth + 1)).collect();
            format!("[ {} ]", inner.join(", "))
        }
        Value::Object(map) => {
            if map.is_empty() {
                return "{}".into();
            }
            let inner: Vec<String> = map
                .iter()
                .map(|(k, v)| {
                    let key = if k
                        .chars()
                        .all(|c| c.is_alphanumeric() || c == '_' || c == '$')
                        && !k.is_empty()
                    {
                        k.clone()
                    } else {
                        format!("'{k}'")
                    };
                    format!("{key}: {}", inspect(v, depth + 1))
                })
                .collect();
            format!("{{ {} }}", inner.join(", "))
        }
    }
}

// --- fetch / sendRequest -----------------------------------------------------------------

fn fetch_bridge<'js>(ctx: Ctx<'js>, req: Object<'js>) -> rquickjs::Result<Object<'js>> {
    let url: String = req.get("url").unwrap_or_default();
    let method: String = req.get("method").unwrap_or_else(|_| "GET".into());
    let body: Option<String> = req.get("body").ok();
    let headers: Vec<(String, String)> = req
        .get::<_, Object<'js>>("headers")
        .map(|h| {
            h.keys::<String>()
                .filter_map(|k| k.ok())
                .filter_map(|k| h.get::<_, String>(&*k).ok().map(|v| (k, v)))
                .collect()
        })
        .unwrap_or_default();

    let reply = match http_call(&method, &url, &headers, body.as_deref()) {
        Ok(v) => v,
        Err(e) => return Err(throw(ctx, &format!("fetch failed: {e}"))),
    };
    let bytes = reply.body;

    let out = Object::new(ctx.clone())?;
    out.set("status", reply.status)?;
    out.set("statusText", reply.status_text)?;
    let hs = Object::new(ctx.clone())?;
    for (k, v) in &reply.headers {
        hs.set(k.to_ascii_lowercase(), v.as_str())?;
    }
    out.set("headers", hs)?;
    // Text when it is text; base64 otherwise — the shim decodes on that flag.
    match String::from_utf8(bytes.clone()) {
        Ok(text) => {
            out.set("body", text)?;
            out.set("bodyEncoding", "utf8")?;
        }
        Err(_) => {
            out.set(
                "body",
                base64::engine::general_purpose::STANDARD.encode(&bytes),
            )?;
            out.set("bodyEncoding", "base64")?;
        }
    }
    Ok(out)
}

/// `rq.sendRequest` — the same call, in the envelope the run-request shim expects.
fn run_request_bridge<'js>(
    ctx: Ctx<'js>,
    descriptor: Object<'js>,
) -> rquickjs::Result<Object<'js>> {
    let started = Instant::now();
    let url: String = descriptor.get("url").unwrap_or_default();
    let method: String = descriptor.get("method").unwrap_or_else(|_| "GET".into());
    let body: Option<String> = descriptor.get("body").ok();
    let headers: Vec<(String, String)> = descriptor
        .get::<_, Object<'js>>("headers")
        .map(|h| {
            h.keys::<String>()
                .filter_map(|k| k.ok())
                .filter_map(|k| h.get::<_, String>(&*k).ok().map(|v| (k, v)))
                .collect()
        })
        .unwrap_or_default();

    let out = Object::new(ctx.clone())?;
    match http_call(&method, &url, &headers, body.as_deref()) {
        Ok(reply) => {
            let r = Object::new(ctx.clone())?;
            r.set("code", reply.status)?;
            r.set("status", reply.status_text)?;
            r.set("responseTime", started.elapsed().as_millis() as f64)?;
            let hs = Object::new(ctx.clone())?;
            for (k, v) in &reply.headers {
                hs.set(k.as_str(), v.as_str())?;
            }
            r.set("headers", hs)?;
            r.set("body", String::from_utf8_lossy(&reply.body).into_owned())?;
            out.set("response", r)?;
        }
        Err(e) => {
            out.set("error", e.to_string())?;
        }
    }
    Ok(out)
}

/// What one HTTP call gives back: status, reason, headers, bytes.
struct HttpReply {
    status: u16,
    status_text: String,
    headers: Vec<(String, String)>,
    body: Vec<u8>,
}

/// One blocking HTTP call on the same client the rest of rq uses.
fn http_call(
    method: &str,
    url: &str,
    headers: &[(String, String)],
    body: Option<&str>,
) -> Result<HttpReply> {
    let agent = ureq::Agent::new_with_defaults();
    let mut builder = ureq::http::Request::builder()
        .method(method.to_ascii_uppercase().as_str())
        .uri(url);
    for (k, v) in headers {
        builder = builder.header(k.as_str(), v.as_str());
    }
    let request = builder
        .body(body.unwrap_or_default().to_string())
        .with_context(|| format!("building the request for {url}"))?;
    let mut resp = agent.run(request)?;
    let status = resp.status().as_u16();
    let status_text = resp.status().canonical_reason().unwrap_or("").to_string();
    let resp_headers: Vec<(String, String)> = resp
        .headers()
        .iter()
        .map(|(k, v)| {
            (
                k.as_str().to_string(),
                v.to_str().unwrap_or_default().to_string(),
            )
        })
        .collect();
    let bytes = resp.body_mut().read_to_vec()?;
    Ok(HttpReply {
        status,
        status_text,
        headers: resp_headers,
        body: bytes,
    })
}

// --- cookies -----------------------------------------------------------------------------

/// `rq.cookies.jar(host)`, in memory for the run. A CLI process has no browser cookie store
/// to speak for, and inventing persistence would be claiming more than we do.
fn cookie_bridge<'js>(
    ctx: Ctx<'js>,
    args: Object<'js>,
    state: &Rc<RefCell<Collected>>,
) -> rquickjs::Result<Object<'js>> {
    let op: String = args.get("op").unwrap_or_default();
    let host: String = args.get("host").unwrap_or_default();
    let out = Object::new(ctx.clone())?;
    let mut st = state.borrow_mut();
    let jar = st
        .cookies
        .entry(host)
        .or_insert_with(|| Value::Array(Vec::new()));
    let list = jar.as_array_mut().expect("jar is an array");

    match op.as_str() {
        "list" => {
            let json = Value::Array(list.clone()).to_string();
            let parsed: JsValue<'js> = ctx.json_parse(json)?;
            out.set("result", parsed)?;
        }
        "upsert" => {
            let cookie: JsValue<'js> = args.get("cookie")?;
            let as_json: Value = serde_json::from_str(
                &ctx.json_stringify(cookie.clone())?
                    .and_then(|s| s.to_string().ok())
                    .unwrap_or_else(|| "null".into()),
            )
            .unwrap_or(Value::Null);
            let name = as_json
                .get("name")
                .and_then(|n| n.as_str())
                .unwrap_or_default()
                .to_string();
            list.retain(|c| c.get("name").and_then(|n| n.as_str()) != Some(name.as_str()));
            list.push(as_json);
            out.set("result", cookie)?;
        }
        "remove" => {
            let name: String = args.get("name").unwrap_or_default();
            list.retain(|c| c.get("name").and_then(|n| n.as_str()) != Some(name.as_str()));
            out.set("result", true)?;
        }
        "clear" => {
            list.clear();
            out.set("result", true)?;
        }
        _ => {
            out.set("error", "unknown cookie op")?;
        }
    }
    Ok(out)
}

// ---------------------------------------------------------------------------------------
// inflateMutations — ported from inflate-mutations.ts
// ---------------------------------------------------------------------------------------

/// Raw guest mutations → the host-facing `MutationDiff`.
///
/// Ported rather than invented, rule for rule: an existing variable keeps its `syncValue`
/// and only its `localValue` moves; a **secret keeps its type**, so a script set can never
/// downgrade one to plaintext; a new runtime variable gets an empty `syncValue` because it
/// is transient; `null` means unset.
fn inflate_mutations(raw: &Value, context: &Value) -> Value {
    let mut diff = Map::new();
    if let Some(scope) = raw.get("global").filter(|v| !v.is_null()) {
        diff.insert(
            "global".into(),
            inflate_scope(scope, context.get("global"), false),
        );
    }
    if let Some(scope) = raw.get("environment").filter(|v| !v.is_null()) {
        diff.insert(
            "environment".into(),
            inflate_scope(scope, context.get("environment"), false),
        );
    }
    if let Some(scope) = raw.get("runtime").filter(|v| !v.is_null()) {
        diff.insert(
            "runtime".into(),
            inflate_scope(scope, context.get("variables"), true),
        );
    }
    if let Some(scope) = raw.get("collection").filter(|v| !v.is_null()) {
        if let Some(id) = context
            .get("info")
            .and_then(|i| i.get("collectionId"))
            .and_then(|c| c.as_str())
        {
            diff.insert(
                "collection".into(),
                json!({
                    "collectionId": id,
                    "variables": inflate_scope(scope, context.get("collectionVariables"), false),
                }),
            );
        }
    }
    Value::Object(diff)
}

fn inflate_scope(raw: &Value, context_vars: Option<&Value>, is_runtime: bool) -> Value {
    let mut out = Map::new();
    let Some(entries) = raw.as_object() else {
        return Value::Object(out);
    };
    for (key, entry) in entries {
        if entry.is_null() {
            out.insert(key.clone(), Value::Null);
            continue;
        }
        let value = entry.get("value").cloned().unwrap_or_else(|| json!(""));
        let raw_type = entry
            .get("type")
            .and_then(|t| t.as_str())
            .unwrap_or("string");
        let existing = context_vars
            .and_then(|v| v.get(key))
            .filter(|v| v.is_object());
        match existing {
            Some(existing) => {
                let mut merged = existing.as_object().cloned().unwrap_or_default();
                let is_secret = merged.get("type").and_then(|t| t.as_str()) == Some("secret");
                merged.insert("localValue".into(), value);
                if !is_secret {
                    merged.insert("type".into(), json!(raw_type));
                }
                out.insert(key.clone(), Value::Object(merged));
            }
            None => {
                let now = iso_now();
                out.insert(
                    key.clone(),
                    json!({
                        "id": uuid::Uuid::new_v4().to_string(),
                        "syncValue": if is_runtime { json!("") } else { value.clone() },
                        "localValue": value,
                        "type": raw_type,
                        "isEnabled": true,
                        "isPersisted": false,
                        "rank": Value::Null,
                        "createdAt": now, "updatedAt": now,
                        "createdBy": Value::Null, "updatedBy": Value::Null,
                    }),
                );
            }
        }
    }
    Value::Object(out)
}

fn now_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// An ISO-8601 timestamp without pulling in a date library for one field.
fn iso_now() -> String {
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let (days, rem) = ((secs / 86_400) as i64, secs % 86_400);
    // Howard Hinnant's civil_from_days.
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!(
        "{y:04}-{m:02}-{d:02}T{:02}:{:02}:{:02}.000Z",
        rem / 3600,
        (rem % 3600) / 60,
        rem % 60
    )
}
